name: endtest
on:
  workflow_dispatch:
  pull_request:
    branches: [master] #You would need to make sure this is correct every time

jobs:
  run_test_case:
    name: Run test case and check for errors
    runs-on: ubuntu-latest
    #needs: Ideally a job above this will prevent this from running. But for now it will be a manual run
    steps:
      - uses: actions/checkout@master
      - name: Running EndTest test case(s)
        id: endtest_functional_tests
        uses: endtest-technologies/github-run-tests-action@v1.8
#        env: "not required"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          app_id: ${{ secrets.EndTest_app_id }}
          app_code: ${{ secrets.EndTest_app_code }}
          api_request: ${{ secrets.EndTest_api_request }}
          number_of_loops: 10
      - name: Check for errors
        run: |
          if [[ ${{ steps.endtest_functional_tests.outputs.errors }} != 0 ]]; then exit 1; else exit 0; fi
          echo "Please review, ${{ steps.endtest_functional_tests.outputs.errors }} error(s) occurred. View results here: ${{ steps.endtest_functional_tests.outputs.results }}"
      - name: Check for failed test cases
        run: |
          if [[ ${{ steps.endtest_functional_tests.outputs.failed }} != 0 ]]; then exit 1; else exit 0; fi
          echo "Please review, ${{ steps.endtest_functional_tests.outputs.failed }} test case(s) failed. View results here: ${{ steps.endtest_functional_tests.outputs.results }}"